### ISSUE TITLE
MSAs

### ISSUE THREAD

**Issue by christophfeinauer** [OATML-Markslab/Tranception#1]
Hi,

very nice paper, I enjoyed it a lot.

One question: Are the MSAs that you are using for the retrieval available somewhere? If not, do you have a script/snippet for creating them?

Thanks!

**Comment by pascalnotin** [comment]
Dear Christoph,

Thank you for the kind words! 

We will make available all MSAs in the next couple weeks. In the meantime, a description of the process used to obtain them is available in Appendix C of the paper.

Kind regards,
Pascal

**Comment by christophfeinauer** [comment]
OK thanks! I might ask again if I have some question about the exact process.

**Comment by pascalnotin** [comment]
Hi Christoph,

We just made the MSA files available for download (thank you @javiermarchena). Please let us know if any questions!

Best,
Pascal

**Comment by christophfeinauer** [comment]
Possibly stupid question, but where is the download link?

**Comment by javier-marchena-hurtado** [comment]
Hi Christoph! Thank you for your interest! The instructions to download the MSAs are available at the end of the reference files description in the ProteinGym folder.

Best,
Javier

**Comment by christophfeinauer** [comment]
I found it, great, thanks!

**Comment by christophfeinauer** [comment]
Hi,

sorry to bother you again but the first file in the gzip archive seems to be a corrupted zipped file:

```
$ curl -o MSA_ProteinGym.tar.gz https://marks.hms.harvard.edu/ProteinGym/MSA_ProteinGym.tar.gz
$ tar -xf ./MSA_ProteinGym.tar.gz 
$ file ./MSA_ProteinGym/A0A140D2T1_ZIKV_theta0.99_281-804_11-26-2021_b02.a2m 
./MSA_ProteinGym/A0A140D2T1_ZIKV_theta0.99_281-804_11-26-2021_b02.a2m: gzip compressed data, last modified: Mon Jun  6 18:38:38 2022, from Unix, original size modulo 2^32 2142594282
$ gzip -v -t ./MSA_ProteinGym/A0A140D2T1_ZIKV_theta0.99_281-804_11-26-2021_b02.a2m
./MSA_ProteinGym/A0A140D2T1_ZIKV_theta0.99_281-804_11-26-2021_b02.a2m:	
gzip: ./MSA_ProteinGym/A0A140D2T1_ZIKV_theta0.99_281-804_11-26-2021_b02.a2m: unexpected end of file

```

All other files seem to be just plain ASCII MSAs. It's not crucial for me, I just wanted to let you know.

**Comment by javier-marchena-hurtado** [comment]
Hi Christoph! First of all, thank you so much for pointing out these little bugs and making suggestions. You really help us.

Indeed, the first MSA had been corrupted during compression. To solve it, now we used .zip instead of .tar.gz and that solved the problem. We have updated the MSAs and the commands to download them. Thanks again!

Best,
Javier

**Comment by pascalnotin** [comment]
I moved the MSA download instructions to main README and slightly updated the MSA zip file (we were missing the indels MSAs). Everything unzips properly on my end now. 

@christophfeinauer - could you please confirm it addressed the issue for you as well?

Thanks,
Pascal

**Comment by christophfeinauer** [comment]
Hi - looks good to me!
