### ISSUE TITLE
MSA Acquisition for New Proteins

### ISSUE THREAD

**Issue by NOforgetQY** [OATML-Markslab/Tranception#13]
Hello, please allow me to ask you a question again, which may be a rather foolish question.
When I wanted to predict a new protein that wasn't in the proteinGym, I got the alignment file through jackhmmer and used MSA_ Processing got MSA_ Weights.npy. But as I move on to the next step, I find that alignment files need to have the same length for each sequence. Otherwise it will have problems in the following steps：（L87）
[`get_msa_prior`](https://github.com/OATML-Markslab/Tranception/blob/main/tranception/utils/msa_utils.py#L87)
My query sequence length is 575. As mentioned in your paper,
`We explore a range of 9 bit score thresholds, from 0.1 to 0.9. We subsequently select the alignment with the highest number of significant Evolutionary Couplings (ECs)`.
I got my alignment file with the following command:
`jackhmmer --incT 0.1 --cpu 8 
-A ./MSA.sto 
./my_sequence.fasta 
./uniref100.fasta`
However, the alignment file obtained in this way does not guarantee that each sequence will be the same length.
What should I do?
I'm a beginner in this field, so please don't mind being asked this seemingly idiotic question.
I would appreciate it if you could teach me how to do it. Thank you！

**Comment by NOforgetQY** [comment]
I found descriptions of acquiring MSA in some previous research papers(eg. EVmutation、EVH、Deepsequence):
`A default bit score of 0.5 bits/residue was used as a threshold for inclusion unless the alignment yielded <80% coverage of the length of the target domain or if there were not enough sequences (redundancy-reduced number of sequences ≥10L)`
So, I need to set the Inct value to 0.5*L and guarantee that there are >=10L sequences in the MSA, right?
But how do I make them consistent in length in the result?

**Comment by pascalnotin** [comment]
Hello,

The input MSA file needs to be in a2m format similar to the other ProteinGym alignment files (other formats like Stockholm are not supported). Have you tried converting the Stockholm file output from Jackhmmer to a2m? 
There are several ways to do that -- the approach we have relied on is to use the [EVcouplings](https://github.com/debbiemarkslab/EVcouplings) align pipeline: it will first run jackhmmer and then convert the output to a2m. 

Kind regards,
Pascal

**Comment by NOforgetQY** [comment]
So using Jackhmmer's own format conversion isn't possible, is it? eg. (`esl-reformat -o ./A.a2m a2m ./A.sto`)
I will try to use EVcouplings align pipeline to get similar .a2m files in ProeinGym, please allow me to close this issue after all the problems have been solved.
Thank you very much!

**Comment by pascalnotin** [comment]
Using the easel library (eg., `esl-reformat`) that is shipped with Jackhmmer might be another way to achieve the same, but we have not tested/used it here. Please let us know if any issues with either approach.

**Comment by NOforgetQY** [comment]
I finally solved this problem. It seems that I can't simply use the tools attached to Jackhmmer to perform format conversion The length of sequences in a2m is not exactly the same. When I used other methods, I got what I wanted. Once again, thank you very much for your reply. I wish you a happy life.
