### ISSUE TITLE
Exact Usage of `hhfilter`

### ISSUE THREAD

**Issue by brucejwittmann** [OATML-Markslab/Tranception#15]
Hi!

I'm trying to replicate some zero-shot predictions using the MSA Transformer but am having a hard time understanding exactly how the MSAs were preprocessed. I am currently using `hhfilter` to get a minimum coverage of 75% and maximum sequence identity of 90% relative to the query sequence. The exact command I am running is below:

```
hhfilter -i $INFILE -o $OUTFILE -id 90 -cov 75 -v 1 -maxseq $SEQS_IN_MSA
```

Running this on the MSAs downloaded from the links provided in this repository, however, I tend to get far less sequences back than I am expecting. For instance, when processing "A0A1I9GEU1_NEIME_full_11-26-2021_b08.a2m", I find that I have 2911 sequences remaining out of the original 5553. The number of weights provided in the file "A0A1I9GEU1_NEIME_theta_0.2.npy" is 5542, however, and assuming that each weight in the weight file corresponds to one sequence in the processed MSA, I would expect to get 5542 sequences back. Clearly I'm missing something, and I was hoping you could help me figure it out :)

Thanks!

**Comment by pascalnotin** [comment]
Hi Bruce,

Your hhfilter command seems correct to me for the MSA Transformer pre-processing.

The .npy files we provided were obtained using the procedure followed in [Hopf et al.](https://www.nature.com/articles/nbt.3769) which does not apply the particular sequence filtering needed by the MSA Transformer (we only remove fragments with less than 50% coverage iirc -- all other sequences are kept). EVE & DeepSequence models use all these sequences during training. Tranception (with retrieval) applies a slightly different filtering on top, as it filters out sequences in the MSA with very low hamming similarity (< 0.2) to the query sequence. Therefore to cover all possible use cases / models we provide weights for all sequences (except for the aforementioned fragments). 

So for zero-shot predictions w/ MSA Transformer, you will have to first filter sequences w/ hhfilter and then pull the corresponding sequence weights from the .npy file.

Best,
Pascal

**Comment by brucejwittmann** [comment]
Thanks, Pascal! So if I'm understanding correctly, if I filter out just those sequences that align to less than 50% of the query sequence, I should find that the number of remaining sequences matches the number of weights in the weight file?

**Comment by pascalnotin** [comment]
Hi Bruce,

The fragments that are filtered out have less than 50% fill rate in the MSA (ie., more than 50% of gap characters '-'). The full logic used for pre-processing is available [here](https://github.com/OATML-Markslab/Tranception/blob/main/tranception/utils/msa_utils.py#L258-L283). The weights computation logic is [here](https://github.com/OATML-Markslab/Tranception/blob/main/tranception/utils/msa_utils.py#L338-L345).
The parameters we used to generate the original values of the weights are: 
- threshold_sequence_frac_gaps = 0.5
- threshold_focus_cols_frac_gaps = 0.3

If helpful, we are also providing a version of these weights with no column filtering (ie., threshold_focus_cols_frac_gaps=1.0) as discussed [here](https://github.com/OATML-Markslab/Tranception/issues/9).

Best,
Pascal

**Comment by brucejwittmann** [comment]
Perfect. Thank you!
