### ISSUE TITLE
Obtain MSA Transformer ensemble

### ISSUE THREAD

**Issue by RaphaelBouvet** [OATML-Markslab/Tranception#16]
I have a further question similar to https://github.com/OATML-Markslab/Tranception/issues/15.

What was the method used to obtain an ensemble with MSA Transformer when there was less than 384 sequences in the input msa?

According to the paper, you use the same MSA from Tranception with MSA Transformer and the processing steps are as follows :
- filter sequences in the input MSA with HHFilter
```
hhfilter -i $INFILE -o $OUTFILE -id 90 -cov 75 -v 1 -maxseq $SEQS_IN_MSA
```
- sample 384 sequences from the filtered MSA using weights to create the ensemble

However there is still some datasets in ProteinGym with less than 384 sequences before or after the preprocessing.
How did you handle this case?

**Comment by pascalnotin** [comment]
Dear @RaphaelBouvet,

What you describe above is correct (we first filter the MSA, then sample). Regardless of the number of sequences remaining post filtering, we sample sequences from the filtered MSA **with replacement** to obtain the desired number of sequences to be passed to the MSA Transformer. Note that we sample sequences with weights as per the procedure from [Hopf et al](https://www.nature.com/articles/nbt.3769).

Kind regards,
Pascal

**Comment by RaphaelBouvet** [comment]
Thank you Pascal for your response.

Best wishes,
Raphaël
