### ISSUE TITLE
Question about the number of DMS

### ISSUE THREAD

**Issue by violet-sto** [OATML-Markslab/Tranception#17]
Hi! 

In the main paper, it said that there are 87 substitution DMS assays and 7 indel assays. However, in the Figure 1, the total number of ProteinGym is 93. I would like to know what is causing this inconsistency.

In addition, I found that there are 41 assays in Deepsequence, could you please point out which are filtered out?

Thanks!

**Comment by pascalnotin** [comment]
Dear @violet-sto,

That is correct we have 87 substitution DMS assays and 7 indel assays, and there is indeed a typo in Figure 1 -- it should read 94 assays total.
We used all assays from DeepSequence except if there was a more recent / higher quality assay for the same protein (in which case we only kept the latter). Note that we also combined certain assays together (eg., the two assays for the RING and BRCT domains of BRCA1_HUMAN were separate in DeepSequence but combined into a single assay in ProteinGym for consistency).

Kind regards,
Pascal
