### ISSUE TITLE
Bug in creating single mutants ( index)

### ISSUE THREAD

**Issue by smilenaderi** [OATML-Markslab/Tranception#18]
In file design_app/Tranception_Design.ipynb
There is an issue in creating mutants, the position is like below

d```
def create_all_single_mutants(sequence,AA_vocab=AA_vocab,mutation_range_start=None,mutation_range_end=None):

        all_single_mutants[current_AA+str(position+1)+mutated_AA]="".join(mutated_sequence)
```
This must change to

`all_single_mutants[current_AA+str(mutation_range_start+position)+mutated_AA]="".join(mutated_sequence)`

**Comment by pascalnotin** [comment]
Hi @smilenaderi - you are correct about the above. Just fixed the bug [here](https://github.com/OATML-Markslab/Tranception/commit/2ddf40e1db9d2d180d1b5fc9d1b39ad5b04fbb6d). Thanks for flagging!
