### ISSUE TITLE
Identify damaging mutations?

### ISSUE THREAD

**Issue by hamidghaedi** [OATML-Markslab/Tranception#19]
Congratulations on your great work with the Tranception GitHub repository! I am particularly interested in using Tranception to help functionalize mutations and distinguish between "likely benign," "likely pathogenic," and "pathogenic" mutations.

However, after reading through the Tranception paper, I wasn't able to find any clear guidance on how to determine which Tranception score cutoff would indicate that a mutation is pathogenic. I was wondering if you could advise on a reasonable Tranception score threshold that could be used to make such a determination?

I appreciate any guidance or insight that you can offer on this topic

**Comment by pascalnotin** [comment]
Hi @hamidghaedi ,

Thanks for the kind words! The main challenge in using LLMs like Tranception in classification settings is that optimal score cutoffs will likely change depending on the protein family (the likelihood will be likely high for protein families that were more frequent in the training data for instance). As a result some form of calibration is in order, and the best way to do that is an active area of research. One simple approach would be, for each protein family of interest, to score all single AA substitutions and set cutoffs based on the corresponding score distributions. Another idea would be to fit GMMs on these distributions, the same way we did in [EVE](https://www.nature.com/articles/s41586-021-04043-8). 

Hope that helps!

Best,
Pascal

**Comment by pascalnotin** [comment]
Closing the issue - feel free to reopen if any further questions on the above.
