### ISSUE TITLE
How to extract position-specific or global embeddings for a protein sequence to use in a related task?

### ISSUE THREAD

**Issue by adalisan** [OATML-Markslab/Tranception#29]
I want to use the internal sequence representation for Tranception to use in  a related task combining different model embeddings. 
One possibility is getting a global embedding for the particular mutated sequence, and using that along with other sequence embeddings for the prediction task.
I am not 100% sure if the per-residue embeddings  for Tranception are meaningful as in other protein language models.  I do not understand the architecture well enough, but do you have an intuition on whether the per-residue embeddings would be useful or you would only care about the last residue embedding for example? In any case, I would want to get those embedding vectors for a pretrained Tranception model
My question is how would we get those vectors, either using huggingface or with the Tranception package?

**Comment by pascalnotin** [comment]
Hi @adalisan - the per-residue embeddings should be as meaningful as for other PLMs: setting aside the retrieval component, Tranception is a more effective autoregressive transformer architecture for protein modeling compared with vanilla GPT. Note that it has been observed that fine tuning embeddings obtained with a MLM architecture (eg., ESM, ProteinBERT) vs an autoregressive model is more effective in many applications, so it is worth trying both for the particular application you are interested in.  

If you are interested in predicting properties for the full protein, then you probably want to consider all residue-level embeddings (eg., from the last layer). In practice, the resulting tensor is too large and several works have further reduced the dimensionality eg., via mean pooling across sequence length. You may also want to check our more recent work [ProteinNPT](https://openreview.net/forum?id=AwzbQVuDBk) which we found to be very effective for (semi-)supervised tasks.

You can extract the embeddings from Tranception as follows:
```
output = model(**input_batch, return_dict=True, output_hidden_states=True)
embeddings = output.hidden_states
```

**Comment by adalisan** [comment]
Thank you for your thorough answer. I will be looking into ProteinNPT as that seems very relevant for our application.
