### ISSUE TITLE
how to calculate the fitness of a protein equivalent to ESM log_likelihood score script?

### ISSUE THREAD

**Issue by avilella** [OATML-Markslab/Tranception#3]
Dears,

I see that this repo scores highly compared to Facebook's ESM log_likelihood score for protein stability/fitness predictions.

Facebook's ESM repo has a python scrip to calculate the log_likelihood from the 1D sequence input files.

Is there such equivalent script in this repo? If so, how to I call it? I've read the README.md but didn't find anything immediately equivalent.

Thanks in advance,

**Comment by pascalnotin** [comment]
Hi Albert,

The [scoring script](https://github.com/OATML-Markslab/Tranception/blob/main/score_tranception_proteingym.py) allows to  compute the fitness of mutated sequences in the ProteinGym assays. See lines 19-44 for a description of the different argsparse arguments, and this [example bash script](https://github.com/OATML-Markslab/Tranception/blob/main/examples/score_tranception_substitution_benchmark.sh). Please let us know if that does not quite cover the use case you had in mind and we will modify the scoring script / add a new script as needed.

Kind regards,
Pascal

**Comment by pascalnotin** [comment]
Hi Albert,

I added the details from my prior message to the [README](https://github.com/OATML-Markslab/Tranception/blob/main/README.md#fitness-prediction-with-tranception--performance-evaluation-on-proteingym). In particular, the [scoring script](https://github.com/OATML-Markslab/Tranception/blob/main/score_tranception_proteingym.py) helps compute the log likelihood ratios for mutated sequences Vs the wild type sequence for the corresponding protein family. I will be closing the issue but feel free to re-open if there are other functionalities that would be helpful to your work.

Kind regards,
Pascal
