### ISSUE TITLE
TransceptEVE

### ISSUE THREAD

**Issue by twidatalla** [OATML-Markslab/Tranception#30]
Hello,

Is there a github available for TransceptEVE?

Best,
Talal

**Comment by pascalnotin** [comment]
Hi @twidatalla -- the TranceptEVE codebase can be found [here](https://github.com/OATML-Markslab/ProteinGym/tree/main/proteingym/baselines/trancepteve). This [notebook](https://github.com/OATML-Markslab/ProteinGym/blob/main/notebooks/TranceptEVE_example.ipynb) may be helpful as well.
Best,
Pascal
