### ISSUE TITLE
Raw DMS scores not available for download

### ISSUE THREAD

**Issue by StephanHeijl** [OATML-Markslab/Tranception#4]
Hi all, let me start off by thanking you for making this amazing resource public! Your work is much appreciated.

I tried to download the raw DMS files per the instructions in the [reference descriptions file](https://github.com/OATML-Markslab/Tranception/blob/main/proteingym/reference_files_description.md). Unfortunately, both the indel and substitutions URLs yield a 404 error. Will these files still be uploaded?

**Comment by pascalnotin** [comment]
Hi Stephan,

Thank you for the kind words and flagging the issue. The problem should be resolved now. Please let us know if the issue still persists at your end.

Kind regards,
Pascal

**Comment by StephanHeijl** [comment]
Much obliged, this resolved the download issue 👍
