### ISSUE TITLE
Invalid UniProt ID RL401_YEAST

### ISSUE THREAD

**Issue by agitter** [OATML-Markslab/Tranception#5]
The UniProt ID [RL401_YEAST](https://www.uniprot.org/uniprotkb?query=RL401_YEAST) that is associated with three ProteinGym datasets does not appear to be a current valid UniProt Entry Name.  A BLAST search with the target sequence provided returns [RL40A_YEAST](https://www.uniprot.org/uniprotkb/P0CH08) and its paralog [RL40B_YEAST](https://www.uniprot.org/uniprotkb/P0CH09) as perfect matches. Could one of those be the relevant UniProt ID?

My group is working to integrate ProteinGym into our benchmarking. It is helpful for us to cross-reference the DMS datasets with other information in UniProt.

More generally, as I told @pascalnotin at ICML, we're very grateful for your team's work preparing and releasing ProteinGym.  If you need help maintaining it, we'd be interested in talking more.

**Comment by pascalnotin** [comment]
Dear Anthony,

Thank you very much for flagging -- you are correct, the Uniprot ID for RL401_YEAST [changed in 2017](https://www.uniprot.org/uniprotkb/P0CH08/history) and is now RL40A_YEAST. We had a look at other assays in ProteinGym and identified one other assay for which the Uniprot ID was recently updated: B3VI55_LIPST changed to LGK_LIPST [earlier this year](https://www.uniprot.org/uniprotkb/B3VI55/history). Note that for LGK_LIPST the associated canonical sequence is now slightly different after the 2022 update compared to the one in our reference file (which corresponds to the sequence mutated in the DMS assay). 
We are updating our reference file for the substitution benchmark to reflect these two Uniprot ID changes.

Regarding your last point, we started to discuss it internally after ICML and are very much open to collaborate with your group (and other research groups that may be interested) to continue enriching the benchmarks with new assays over time. 

Kind regards,
Pascal

**Comment by agitter** [comment]
Thanks for investigating.  I consider my question closed by b4faa621cf80872831dc89d04f28f996c02ef7bf if you'd like to close this issue, unless you are planning more updates related to LGK_LIPST.

Let's continue discussing how to maintain the benchmarks with new assays in these issues or whatever forum your team finds convenient.

**Comment by pascalnotin** [comment]
Great - thank you for confirming @agitter ! Reference file was updated for LGK_LIPST in the last commit ([4596b66](https://github.com/OATML-Markslab/Tranception/commit/4596b66d8eda48f6eb26725ecbfedb86d64339ff)). Will close the issue now and will be in touch later re: process to review / add new assays.
