### ISSUE TITLE
ProteinGym does not contain wildtype fitness values

### ISSUE THREAD

**Issue by StephanHeijl** [OATML-Markslab/Tranception#6]
Once again thanks for publishing this dataset and being so responsive to questions! Your help with issue #4 has been much appreciated.

An element of information I found absent from the ProteinGym files were the (normalized) fitness values of the wildtype protein. The  binarization cutoff value unfortunately is not the same. These values are also absent from the raw DMS assays as far as I could tell.

If this data is available to you, would it be possible to include this in the ProteinGym dataset?

**Comment by pascalnotin** [comment]
Dear Stephan,

The raw datasets include all information from the original paper we had access to. With that said, several assays include silent mutations which you may use as a proxy for the wild type fitness values (silent mutations are excluded from the processed files, but are present in the raw files for the assays that provide them).

Hope that helps!

**Comment by StephanHeijl** [comment]
Thank you, it appears I was looking at some of the DMS files that did not include any silent mutations, but looking at it again some files do have these. Some even have explicit wildtype fitnesses!

For reference, if anyone is looking for this data, this is what I was able to extract. It doesn't cover everything, but there are at least a few here.
```javascript
{
  "CAPSD-AAV2S-Sinai-substitutions-2021": -0.9181937106929464,
  "A0A2Z5U3Z0-9INFA-Doud-2016": 0,
  "GRB2-HUMAN-Faure-2021": 0.0020161858336449,
  "VKOR1-HUMAN-Chiasson-2020": 1.20881149759008,
  "HSP82-YEAST-Mishra-2016": 0.105360237,
  "DLG4-RAT-McLaughlin-2012": 0.17582,
  "A4D664-9INFA-Soh-2019": 1,
  "A0A140D2T1-ZIKV-Sourisseau-growth-2019": 1,
  "POLG-HCVJF-Qi-2014": 0,
  "TPOR-HUMAN-Bridgford-S505N-2020": 0,
  "KKA2-KLEPN-Melnikov-2014": 1.0041,
  "CP2C9-HUMAN-Amorosi-2021": 1.406341339,
  "RL401-YEAST-Mavor-2016": 0,
  "TPMT-HUMAN-Matreyek-2018": 1.78186957,
  "GCN4-YEAST-Staller-2018": 1.7495189130000002,
  "F7YBW8-MESOW-Aakre-2015": 0,
  "UBC9-HUMAN-Weile-2017": 1,
  "BLAT-ECOLX-Deng-2012": 0,
  "RL401-YEAST-Roscoe-2014": 1.083237574,
  "TPK1-HUMAN-Weile-2017": 1,
  "DYR-ECOLI-Thompson-plusLon-2019": 0,
  "P53-HUMAN-Kotler-2018": 0.217920190983,
  "HSP82-YEAST-Flynn-2019": 0.14080438322195,
  "GFP-AEQVI-Sarkisyan-2016": 3.72635845779234,
  "SUMO1-HUMAN-Weile-2017": 1,
  "A4GRB6-PSEAI-Chen-2020": 0.905644665499,
  "SYUA-HUMAN-Newberry-2020": -0.0126375854708689,
  "Q59976-STRSQ-Romero-2015": 0.021,
  "POLG-CXB3N-Mattenberger-2021": 0,
  "PA-I34A1-Wu-2015": 3.169534812,
  "PTEN-HUMAN-Matreyek-2021": 1.33189147470756,
  "NUD15-HUMAN-Suiter-2020": 0.994725097,
  "C6KNH7-9INFA-Lee-2018": 0,
  "CALM1-HUMAN-Weile-2017": 1,
  "DLG4-HUMAN-Faure-2021": 0.015972913948091,
  "IF1-ECOLI-Kelsic-2016": 1.0825,
  "AMIE-PSEAE-Wrenbeck-2017": 0,
  "KCNH2-HUMAN-Kozek-2020": 142.9424204,
  "BLAT-ECOLX-Firnberg-2014": 1.4256,
  "SPIKE-SARS2-Starr-2020": 0,
  "SC6A4-HUMAN-Young-2021": 0.947166004,
  "SCN5A-HUMAN-Glazer-2019": 74.1,
  "B3VI55-LIPST-Klesmith-2015": 0,
  "RL401-YEAST-Roscoe-2013": 0.027690354667745,
  "BRCA1-HUMAN-Findlay-2018": 0.785939376
}
```

Again thanks for the help!

**Comment by loodvn** [comment]
Could you please share your script to generate these values? I'm looking into something and wanted to do the same thing 👍

**Comment by StephanHeijl** [comment]
@loodvn I created a (slightly cleaned) gist of the script I used here: https://gist.github.com/StephanHeijl/ce7686d4d67db744c55bf7ed109de069
Note that it makes some assumptions about what constitutes a wildtype value (like silent mutations not resulting in a change in fitness) and only looks at the DMS values. If you want to make sure that the wildtype fitness is correct you will have to check the literature. I make no guarantees that the values generated by the script are 100% correct ;)
