### ISSUE TITLE
How could I gain the raw MSA with every complete sequence in Tranception?

### ISSUE THREAD

**Issue by lsw9803** [OATML-Markslab/Tranception#8]
Dears,

To my understanding, the MSA data used in the work has been preprocessed to make sure the every column
has enough aligned AAs. However in my proceeding research, I need the raw MSA data including every complete sequence of your work desperately. In my practice, the pipeline developed by Debora Marks Lab called “Evcouplings” contained the raw “.sto” files in “align” stage, which is required for my next step research. I’d appreciate it very much if you could spare some time to provide the raw MSA data.

Sincerely
Shiwei Liu

**Comment by pascalnotin** [comment]
Dear Shiwei,

I just responded to you over email, but copying the information below as well in case it is helpful to others:

You may download the .sto files as follows:

curl -o ProteinGym_substitution_sto_files.zip https://marks.hms.harvard.edu/tranception/sto_files/ProteinGym_substitution_sto_files.zip

curl -o ProteinGym_indel_sto_files.zip https://marks.hms.harvard.edu/tranception/sto_files/ProteinGym_indel_sto_files.zip

Please note that the files are ~4.5GB when zipped, and ~70GB when unzipped.

Let me know if that addresses the issue or if you have any questions.

Kind regards,
Pascal
